---
- name: install apache in servers
  hosts: all
  tasks: 
    - name: install apache in ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: install apache in amazon
      when: ansible_distribution == "Amazon"
      yum: 
        name: httpd
        state: present
        update_cache: yes
    - name: Ensure Apache service is running
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes
     
