---
- name: Reboot system
  hosts: all
  tasks: 
    - name: reboot if kernel upgraded
      reboot:
        msg: reboot the system to apple the new kernel
        reboot_timeout: 300
        pre_reboot_delay: 0
    - name: wait for hosts to come back online
      wait_for_connection:
        delay: 30
        tiome_out: 300
 